#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 22:14:51 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=photon_v1.3b.zip
